[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tungstenite = "0.26.2"
warp = "0.3"
futures = "0.3"
uuid = { version = "1.3", features = ["v4"] }
